{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "k8s-auto-labeller.serviceAccountName" . }}
  labels:
    {{- include "k8s-auto-labeller.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "watch", "update", "get"]
{{- end }}
