{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "k8s-auto-labeller.serviceAccountName" . }}
  labels:
    {{- include "k8s-auto-labeller.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "k8s-auto-labeller.serviceAccountName" . }}
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: {{ include "k8s-auto-labeller.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
