{{- if .Values.rbac.create -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:{{ include "ncs2-device-plugin.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ncs2-device-plugin.serviceAccountName" . }}
    namespace: {{ .Values.serviceAccount.namespace }}
roleRef:
  kind: ClusterRole
  name: system:{{ include "ncs2-device-plugin.serviceAccountName" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end -}}
