{{- if .Values.rbac.create -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:{{ include "ncs2-device-plugin.serviceAccountName" . }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list", "patch", "update", "get"]
{{- end -}}
