{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ncs2-device-plugin.serviceAccountName" . }}
  {{- if .Values.serviceAccount.namespace }}
  namespace: {{ .Values.serviceAccount.namespace }}
  {{- end }}
  labels:
    {{- include "ncs2-device-plugin.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
