{{- if .Values.rbac.create -}}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:{{ include "k8s-node-label-monitor.serviceAccountName" . }}
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list", "watch"]
{{- end -}}
