apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-node-label-monitor.fullname" . }}
  labels:
    {{- include "k8s-node-label-monitor.labels" . | nindent 4 }}
  namespace: {{ .Values.serviceAccount.namespace }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "k8s-node-label-monitor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "k8s-node-label-monitor.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "k8s-node-label-monitor.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.podEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.labelMonitor }}
          args:
            {{- if not .Values.labelMonitor.logging }}
            - "-logging=false"
            {{- end -}}
            {{- if .Values.labelMonitor.cronjob }}
            - "-cronjob={{ .Values.labelMonitor.cronjob }}"
            {{- end -}}
            {{- if .Values.labelMonitor.notificationUrl }}
            - "-endpoint={{ .Values.labelMonitor.notificationUrl }}"
            {{- end -}}
          {{- end -}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
