{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-node-label-monitor.serviceAccountName" . }}
  {{- if .Values.serviceAccount.namespace }}
  namespace: {{ .Values.serviceAccount.namespace }}
  {{- end }}
  labels:
    {{- include "k8s-node-label-monitor.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
